INSDIR=/var/www/html/boolean_search

install: booleansearch.app.js index.html
	mkdir -p $(INSDIR)
	cp booleansearch.app.js index.html $(INSDIR)/
	mkdir -p $(INSDIR)/styles
	cp styles/*.css $(INSDIR)/styles/
	